### ISSUE TITLE
Some Sintax sugar

### ISSUE THREAD

**Issue by maxodrom** [lav45/yii2-settings#7]
Привет!
Если будет такая возможность, то нельзя ли было бы добавить немного синт. сахара для методов `Settings::get($key)` и `Settings::set($key, $value)`, работающих в паре?

Метод get() часто возвращает NULL, когда зчачения нет в хранилище.

Можно реализовать что-то по аналогии с методом `getOrSet()`, который есть в Yii2 (компонент `cache`) https://www.yiiframework.com/doc/guide/2.0/ru/caching-data#kesirovanie-dannyh

Например по аналогии с использованием Yii2 cache писать что-то вроде:
```php
$data = $settings->getOrSet($key, function () {
    return $this->calculateSomething();
});
```

или

```php
$user_id = 42;
$data = $settings->getOrSet($key, function () use ($user_id) {
    return $this->calculateSomething($user_id);
});
```

Было бы неплохо иметь такую возможность, вместо этого: 
```php
$data = $settings->get($someKey);
if ($data === null /* или someValue */) {
    $data = .... // устанавливаем значение...
    $settings->set($someKey, $data);
}
```

**Comment by lav45** [comment]
```php
$user_id = 42;
$data = $settings->getOrSet($key, function () use ($user_id) {
    return $this->calculateSomething($user_id);
});
```

Settings !== Cache

Настройки хранят значение которое установил пользователь или возвращает default
Как вариант можешь использовать в качестве default значения callback функцию и там выполнить свой код.

```php
/**
 * @sing 1.3.2
 */
 Yii::$app->settings->get($key, function () use ($user_id) {
    return $this->calculateSomething($user_id);
});
```

**Comment by maxodrom** [comment]
Да, спасибо за ответ. Буду пробовать )
